# Generated by Django 2.2.1 on 2019-05-13 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('(01)[0-9]{9}', message='phone number is not valid')]),
        ),
    ]
