# Generated by Django 2.2.1 on 2019-05-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
