# Generated by Django 2.2.1 on 2019-05-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reports',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
