# Generated by Django 2.2.1 on 2019-05-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reports',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='reports',
            field=models.IntegerField(default=0),
        ),
    ]
